// File generated by dotnet-combine at 2023-09-10__12_06_23

using AlgoTester.Helpers;
using static AlgoTester.Helpers.ConsoleHelper;
using static System.Console;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;



// Helpers/ConsoleHelper.cs
namespace AlgoTester.Helpers
{
    public static class ConsoleHelper
    {
        public static int ReadInt()
        {
            return int.Parse(Console.ReadLine());
        }

        public static IEnumerable<T> ReadItems<T>(int count, Func<string, T> parser)
        {
            return Enumerable.Range(0, count).Select(_ => parser(Console.ReadLine()));
        }
    }
}

// Helpers/GraphsHelper.cs
namespace AlgoTester.Helpers
{
    public static class GraphsHelper
    {
        public static List<T> GetBfsShortestPath<T>(this IEnumerable<T> items, Func<T, T, bool> isConnectedPredicate,
            T start, T end)
        {
            var queue = new Queue<T>();
            var visited = new HashSet<T>();
            var parents = new List<(T Parent, T Child)>();

            queue.Enqueue(start);
            visited.Add(start);

            while (queue.Count > 0)
            {
                var current = queue.Dequeue();

                if (current.Equals(end))
                {
                    break;
                }

                var childrenItems = items.Where(x => !visited.Contains(x) && isConnectedPredicate(current, x))
                    .ToList();

                foreach (var item in childrenItems)
                {
                    queue.Enqueue(item);
                    visited.Add(item);

                    parents.Add((current, item));

                    if (item.Equals(end))
                    {
                        break;
                    }
                }
            }

            var path = new List<T>();

            if (!parents.Any(parentPair => parentPair.Child.Equals(end)))
            {
                if (visited.Contains(end))
                {
                    return path;
                }

                throw new InvalidOperationException("No path found");
            }

            var currentItem = end;

            while (!currentItem.Equals(start))
            {
                path.Add(currentItem);

                currentItem = parents.First(parentPair => parentPair.Child.Equals(currentItem)).Parent;
            }

            return path;
        }
    }
}

// Program.cs
namespace AlgoTester.WordGame2
{
    public static class Program
    {
        private const int WrongAnswer = -1;

        public static void Main()
        {
            try
            {
                var wordsCount = ReadInt();
                var words = ReadItems(wordsCount, str => str).ToList();

                var path = words.GetBfsShortestPath(CanGoToNextWord, words.First(), words.Last());
                
                WriteLine(path.Count);
            }
            catch (Exception e)
            {
                WriteLine(e.Message);
                WriteLine(WrongAnswer);
            }
        }

        private static bool CanGoToNextWord(string currentWord, string nextWord)
        {
            return currentWord[currentWord.Length - 2] == nextWord[1];
        }
    }
}
